### ISSUE TITLE
Scrolling messes up embedded terminal layout

### ISSUE THREAD

**Issue by bcyrill** [dobin/lxd-webgui#1]
When scrolling in the embedded Terminal (Containers view) the content gets messed up (e.g. line breaks appear).

![image](https://cloud.githubusercontent.com/assets/1117411/14232963/6d1ba4e6-f9ba-11e5-948b-69cd7afd0fca.png)

**Comment by dobin** [comment]
Yes, i could reproduce it. Its also the same issue on https://linuxcontainers.org/lxd/try-it

Maybe i have to update on xterm.js (fork of term.js)
