### ISSUE TITLE
LXD 2.0: Empty Used By field in network details

### ISSUE THREAD

**Issue by ghost** [dobin/lxd-webgui#17]

**Comment by dobin** [comment]
According to the REST API, it should contain data: https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10networksname

maybe a bug in LXD? Or only appearing under certain conditions?

**Comment by ghost** [comment]
Re-checked my configuration. I got NAT with static IPs to release my router's DHCP. When I go to `Networks` section, I see that network type is `unknown`. Well, I think you're right and issue is related to LXD.

**Comment by dobin** [comment]
Actually, the "used_by" field is only available in bridges. I fix it atm.
