### ISSUE TITLE
Starting / Stopping container closes embedded terminal

### ISSUE THREAD

**Issue by bcyrill** [dobin/lxd-webgui#2]
When starting or stopping another container the embedded terminals are closed and their content lost.

**Comment by dobin** [comment]
Will be soon fixed.

**Comment by dobin** [comment]
I think this is fixed with a3bbe98fd356241f6e6043d6860fe4af8728dee0

**Comment by bcyrill** [comment]
works perfectly now.

**Comment by dobin** [comment]
Awesome :-)
