### ISSUE TITLE
Test with LXD 2.0

### ISSUE THREAD

**Issue by dobin** [dobin/lxd-webgui#3]
LXD 2.0 is released. Test it, especially:

GET /1.0/containers/NAME for performance reasons no longer returns the detailed container runtime status ("status" key), a separate query to /1.0/containers/NAME/state is now needed

lxd/core: Add a new /logs REST API to containers

**Comment by dobin** [comment]
No issues till now. Yay.

**Comment by faddat** [comment]
I may be having an lxd 2.0 issue.  Not totally sure:

Apr 23 08:09:09 arch-anywhere lxd[29972]: 2016/04/23 08:09:09 http: TLS handshake error from 127.0.0.1:51054: EOF
Apr 23 08:09:12 arch-anywhere lxd[29972]: 2016/04/23 08:09:12 http: TLS handshake error from 127.0.0.1:51074: EOF
Apr 23 08:09:15 arch-anywhere lxd[29972]: 2016/04/23 08:09:15 http: TLS handshake error from 127.0.0.1:51082: EOF
Apr 23 08:09:18 arch-anywhere lxd[29972]: 2016/04/23 08:09:18 http: TLS handshake error from 127.0.0.1:51090: EOF
Apr 23 08:09:21 arch-anywhere lxd[29972]: 2016/04/23 08:09:21 http: TLS handshake error from 127.0.0.1:51098: EOF
Apr 23 08:09:21 arch-anywhere lxd[29972]: 2016/04/23 08:09:21 http: TLS handshake error from 127.0.0.1:51110: EOF
Apr 23 08:09:24 arch-anywhere lxd[29972]: 2016/04/23 08:09:24 http: TLS handshake error from 127.0.0.1:51124: EOF
Apr 23 08:09:27 arch-anywhere lxd[29972]: 2016/04/23 08:09:27 http: TLS handshake error from 127.0.0.1:51132: EOF
Apr 23 08:09:30 arch-anywhere lxd[29972]: 2016/04/23 08:09:30 http: TLS handshake error from 127.0.0.1:51140: EOF
Apr 23 08:09:33 arch-anywhere lxd[29972]: 2016/04/23 08:09:33 http: TLS handshake error from 127.0.0.1:51148: EOF

(from systemctl status lxd)

the TLS does seem to work at some point though:  

![screenshot from 2016-04-23 08-10-57](https://cloud.githubusercontent.com/assets/7142025/14758407/f5503a64-092a-11e6-8fd8-d07db9f42df3.png)

**Comment by dobin** [comment]
Yes i have the same error. 

But i think it's because lxd-webgui tries to access the LXD rest service via ajax, but the user did not yet accept the (not really valid) certificate of the rest service. I'll research some more.
