### ISSUE TITLE
I am seeing only setting page. Why?

### ISSUE THREAD

**Issue by fatihusta** [dobin/lxd-webgui#33]
Menu button not working
![1](https://cloud.githubusercontent.com/assets/11256228/21770796/804926be-d68d-11e6-9e07-88fe2cc0a7fa.png)

```
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"config":{"core.https_address":"127.0.0.1:9000","core.https_allowed_credentials":"true","core.https_allowed_headers":"Origin, X-Requested-With, Content-Type, Accept","core.https_allowed_methods":"GET, POST, PUT, DELETE, OPTIONS","core.https_allowed_origin":"https://localhost:8000","core.trust_password":true},"api_extensions":["storage_zfs_remove_snapshots","container_host_shutdown_timeout","container_syscall_filtering","auth_pki","container_last_used_at","etag","patch","usb_devices","https_allowed_credentials","image_compression_algorithm","directory_manipulation","container_cpu_time","storage_zfs_use_refquota","storage_lvm_mount_options","network","profile_usedby","container_push","container_exec_recording","certificate_update","container_exec_signal_handling","gpu_devices","container_image_properties","migration_progress","id_map","network_firewall_filtering","network_routes"],"api_status":"stable","api_version":"1.0","auth":"trusted","public":false,"environment":{"addresses":["127.0.0.1:9000"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----\nMIIFZDCCA0ygAwIBAgIQfSj+rrNivuuNYB3+XWLzGjANBgkqhkiG9w0BAQsFADA8\nMRwwGgYDVQQKExNsaW51eGNvbnRhaW5lcnMub3JnMRwwGgYDVQQDDBNyb290QGZz\nbS1WaXJ0dWFsQm94MB4XDTE3MDEwOTEyMDMzNFoXDTI3MDEwNzEyMDMzNFowPDEc\nMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEcMBoGA1UEAwwTcm9vdEBmc20t\nVmlydHVhbEJveDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOD8XOpX\nJ7A9cmdc20+8ta9OzDNJn5muBv1Huy1rE1Mb+vrMfhh5KgLLeGvLEqeDZo+uoRmS\n37Ane/vXKusTqrh0oSE/Airdy67xowHIxZfQx0zvRWxvnlK3waJ4q/tit4/CNsvb\nRL7cfQ5KRP7xlHETOQWy+VxiVcPhmZ+/+i9xUyus/vsMwdwmw7E/H2MxbjIeHJ2W\n0Vsl7lgVXfx7yHiGDaBHIjs2b5el5Nbld+x6ZSiDROg9X7WZS9mDHVrVKvIwYGI+\nxAQMcpZkJ9d0bsCV1YkQVe6ogK0G8A3nX9+9fxdE9H1DclizVvnWAtw1mv3R9yuq\nI0u8z5pV1akP6EXyZJ6dMQkjCtLQYm6IIMS3KTb0FkbSvCH03LzMrW7qnQfo2DGa\nYGwf168qj5Qx/eCEvuaYegGDyMVVE93JOpueIB6Ml2Fgm3HzBl8hHbzS9nf+IzAY\npQalR21PLhmCAeXaaX8HKLKdSTVO2zp176MkoXhRIlZWF6b5FZtdPmjbTjPuKZF/\nOnFhKP3qvX6WierAPBGQTQHlq2nI/9DSU73H5MQerjM05N95+e3Bzqa9AY7xbohr\nfTNWFEQnbppVOidsrqSBDwAUK8Pb0TKVTc1ORBoqE2XEb/nj/un327iURdvOkPPE\nkZYE9pBikNl1HBRtoYUa1gGJjOf9dZjKgBlbAgMBAAGjYjBgMA4GA1UdDwEB/wQE\nAwIFoDATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCsGA1UdEQQk\nMCKCDmZzbS1WaXJ0dWFsQm94hwQKAAIPhwQKAAMBhwSsEQABMA0GCSqGSIb3DQEB\nCwUAA4ICAQCyMTc+PIF5ZfZOOZMxf18dmSmLTAk7+RDUzbo0VUTFg303slfvB1LF\nKNbFoIa4W7d0FPI5Vbs1+rQFLEI+rIucDtvAYAfDOrVMHbpIgWO4gFROEjAIlgrS\nJuV3FMZzmSVZY3EiFKrgwU2g+aVVR0KB1O7wD8OhNaoPhqfG0zoXR4z6J+E7TVGb\nHFbb+5WXl+4IRFPw5yaMaXbNuvt755bARmayQ6wORHLM9CY8qYyzIhZMft7QUhtZ\ntHqQjacRjWsst7b8SPjVQeMl3E3jjplJKvpcYoTFvzzFAfzpgtUIaXGwwGh+Ypnh\nCO3t3an8KBN705G1z/hEEJzNaRkMKDla/+pCWlwlrt7l/NbX8q4BxSZ5jDdEX21g\nbcGZwWkp7eKlwEHyTMWt/gmkB16UK1ywDyAH2NSsJ57a3Qzo1DzPNL4/HRamL+St\nYW7t4rznnmLdhNN0U1XZMH+/HUGfWFFrK8bhmMbpKDzeNgQtJ8LOyTrTu15wx+lr\nzdqGNm/qFdrrLpCKOO/AgR/TdTfyNcR555xRc+CLoE+n7PsccYT/W4DgnZ1ut30d\nScVd4PL6KkmvIE6PobWELA11e9KgPcMbndemNqOEHh5AOzd4S5zekg6sI36RdBP4\nASWy7UxLUS32vH01WaWSR2Jl0fehqUi5/DHRpgyX1GoPCmIwLaAAOg==\n-----END CERTIFICATE-----\n","certificate_fingerprint":"","driver":"lxc","driver_version":"2.0.6","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-57-generic","server":"lxd","server_pid":30319,"server_version":"2.7","storage":"dir","storage_version":""}}}
```

**Comment by dobin** [comment]
What do you mean "Menu button not working" ? If you click for example on the menu entry "Containers" or "Images", no new page will appear?

**Comment by fatihusta** [comment]
Yes, exactly. Please look screenshot url.

**Comment by dobin** [comment]
If you press F12 and check the network traffic, do you see failed HTTP requests?

**Comment by fatihusta** [comment]
No fail request.
when I write link manualy then work. But clik not working.

Screenshot1 for manual
![2](https://cloud.githubusercontent.com/assets/11256228/21771865/c21626f6-d691-11e6-931f-ecf4b31cd543.png)

Screenshot2 for Clicked

![3](https://cloud.githubusercontent.com/assets/11256228/21771893/e9bb9d08-d691-11e6-8eb7-c3ad819f403d.png)

**Comment by cfriedel** [comment]
I am having the same issue.  If you try to click any other menu option other than Settings, it will just take you back to the settings page.  I have replicated this in both Chromium and Chrome.  Here is my LXD URL information if that helps

<code>
{"type":"sync","status":"Success","status_code":200,"metadata":{"api_extensions":["storage_zfs_remove_snapshots","container_host_shutdown_timeout","container_syscall_filtering","auth_pki","container_last_used_at","etag","patch","usb_devices","https_allowed_credentials","image_compression_algorithm","directory_manipulation","container_cpu_time","storage_zfs_use_refquota","storage_lvm_mount_options","network","profile_usedby","container_push","container_exec_recording","certificate_update","container_exec_signal_handling","gpu_devices","container_image_properties","migration_progress","id_map","network_firewall_filtering","network_routes"],"api_status":"stable","api_version":"1.0","auth":"trusted","config":{"core.https_address":"127.0.0.1:9000","core.https_allowed_credentials":"true","core.https_allowed_headers":"Origin, X-Requested-With, Content-Type, Accept","core.https_allowed_methods":"GET, POST, PUT, DELETE, OPTIONS","core.https_allowed_origin":"https://localhost:8000","core.trust_password":true},"environment":{"addresses":["127.0.0.1:9000"],"architectures":["x86_64","i686"],"certificate":"-----BEGIN CERTIFICATE-----

Certificate Removed

-----END CERTIFICATE-----\n","driver":"lxc","driver_version":"2.0.6","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.4.0-47-generic","server":"lxd","server_pid":6812,"server_version":"2.7","storage":"dir","storage_version":""},"public":false}}
</code>

Here is the version of Linux I am running
<code>
cliff@reventon ~ $ cat /proc/version
Linux version 4.4.0-47-generic (buildd@lcy01-03) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016
</code>

If there is any additional information I can provide, please let me know.

**Comment by dobin** [comment]
Thanks for the feedback. In my case (up to date Ubuntu 16.04) it still works how it should.

From the screenshot of you guys, i see that your URL's are in style "localhost:8000/#!/settings", whereas with my installation I got the standard AngularJS "localhost:8000/#/settings" (without the exclamation mark !). 

I assume that AngularJS changed the behavior, and that you guys have a newer version than me (via NPM install). And that i seem to construct AngularJS the lazy static way, and not the Angular way .

Anyway I commited a patch, could you do a git pull and test again? Thanks

**Comment by fatihusta** [comment]
I tested. It's worked. Thank you very much.

**Comment by cfriedel** [comment]
It works for me as well.  Thank you!

**Comment by dobin** [comment]
awesome! Thanks guys.
