### ISSUE TITLE
Change the default address 127.0.0.1:9000

### ISSUE THREAD

**Issue by saldru** [dobin/lxd-webgui#6]
@dobin I want to change the default address that the LXD WebGUI search because, when I clean web cache, the LXD WebGUI return to search on https://127.0.0.1:9000. I want to have an other default IP Address.

How can I do that ? Thanks

**Comment by aarnaud** [comment]
Hi @saldru 

The settings are save in the localStorage, when you clear the browser cache you remove it.

**Comment by dobin** [comment]
@aarnaud is correct :-) 

I store the settings in localStorage in the browser (as there is no backend), and if you clean the browser cache the localStorage with the LXD WEBGUI is getting cleaned too. Intentional design decision.
