### ISSUE TITLE
Problem with Keyboard char in Terminal

### ISSUE THREAD

**Issue by saldru** [dobin/lxd-webgui#7]
@dobin I'm using a french AZERTY keyboard and to type `@` or `[`, `}`, `\`, I will use a combinaison keys like  `Alt Gr + 8` for `\` ,  `Alt Gr + 0` for `@` etc... 

In the Web Terminal, these keys do not work. I'm not able to type an `@` or `#`. 
It's a problem to do an SSH connection like `user@domain.com` 

Could you solve it please. Thank you.

**Comment by aarnaud** [comment]
@saldru can you try on https://github.com/aarnaud/lxd-webui because i don't reproduce.

**Comment by saldru** [comment]
@aarnaud It's working fine with your web service but not with @dobin web gui.

**Comment by dobin** [comment]
Strange. I'll investigate.

**Comment by dobin** [comment]
Could not reproduce. 

I changed keyboard layout in ubuntu to "french", and i was able to insert the `@[`.

Can you tell me your OS + Browser?

**Comment by dobin** [comment]
Could not reproduce, no feedback.
